fix: use SAMtools to compress reference genome
zavolanlab/mirflowz pull request #139
Opened 2024-02-07 14:03 UTC by deliaBlue

This PR closes #138 .

In order to use `bgzip` when running the pipeline with Conda, the SAMtools micro-environment is used in the `compress_reference_genome` rule in `pileup.smk`

2024-02-07 14:04 UTC, deliaBlue commented
The format test does not pass as the fix is done in the PR #137 and it is not yet merged.

2024-02-23 16:57 UTC, uniqueg requested changes
I'm not sure how the proposed changes match the title of this PR or the referenced issue (which, admittedly, I don't quite understand)

2024-02-23 17:48 UTC, deliaBlue commented
The issue behind this PR was opened because when trying to use `bgzip` when running the pipeline using Conda, the command could not be found - I have it installed locally and I thought it was on every machine.

2024-03-18 12:22 UTC, uniqueg commented on workflow/rules/quantify.smk
> +            mir=[mir for mir in config["mir_list"] if mir != "isomir"],
But this looks like something unrelated to the environment issue? Are you trying to sneak something past me here? :raised_eyebrow::laughing: 

Or is this some artifact from another PR?

2024-05-18 14:15 UTC, uniqueg approved these changes

2024-07-31 13:05 UTC, merged