refactor: workflow cleanup
zavolanlab/mirflowz pull request #98
Opened 2023-07-25 21:14 UTC by deliaBlue

This PR closes #91 .

The changes in this PR are:

- Change all "premir" by "primir" (in rules, output files, scripts and test files)
- Change rule names to make them more meaningful
- Update expected output as some output file names have changed.
- Update `cluster.json` to match rule names and remove unused configuration.

2023-08-15 13:30 UTC, uniqueg requested changes

2023-08-15 13:30 UTC, uniqueg commented on workflow/rules/prepare.smk
> +        exteneded_primir=expand(
Should be `extended_primir`, not `exteneded`

2023-08-15 13:30 UTC, uniqueg commented on workflow/rules/prepare.smk
> +rule trim_fasta_seqs_id:
Better `trim_fasta_seq_ids`, no?

2023-08-31 00:21 UTC, deliaBlue commented
In this push, some extra changes have been add:

- log files now match the rule name
- Output file names are build to be found together (_i.e_ all the alignments start by `alignments`, all `segemehl` outputs start by `segemehl`, so on and so forth).
- All 4 snakefiles have been lint with `snakefmt -l 80`
- The `{sample}` wildcard has been removed from some output files as they will already be stored in the `sample` directory.

As a suggestion, some script names should be changed by the same reason as [this comment](https://github.com/zavolanlab/mirflowz/pull/98#discussion_r1294593218) was made.

As a detail, rule headers could also be modified (some of them) to be more specific.

2023-08-31 21:41 UTC, uniqueg requested changes
A few slight changes for consistent rule names. It seems the file names are still not super consistent, but I didn't comment on that because it would have been too much. Also, it's really not that important.

2023-08-31 21:41 UTC, uniqueg commented on workflow/rules/prepare.smk
> +rule exons_gtf_to_bed:
Better would be to keep the naming policy and start with a verb, e.g., `convert_`

2023-08-31 21:41 UTC, uniqueg commented on workflow/rules/map.smk
> +            config["cluster_log"], "collapse__identical_reads_{sample}.log"
Use only one `_`

2023-08-31 21:41 UTC, uniqueg commented on workflow/rules/map.smk
> +rule oligomap_genome_to_sam:
Start with a verb, e.g., `comvert_genome_to_sam_oligomap`

2023-08-31 21:41 UTC, uniqueg commented on workflow/rules/map.smk
> +rule oligomap_transcriptome_to_sam:
As above

2023-08-31 22:06 UTC, uniqueg approved these changes

2023-08-31 22:23 UTC, merged